spring.application.name=vehicle-service
server.port=8080

#spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_db
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/vehicle_db
spring.datasource.username=root
spring.datasource.password=milica221/22

spring.config.import=optional:configserver:http://localhost:8888

resilience4j.circuitbreaker.instances.vehicleServiceCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.vehicleServiceCircuitBreaker.minimum-number-of-calls=5

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka


